// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewAgent.Data;

#nullable disable

namespace ReviewAgent.Data.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    [Migration("20260817180958_InitialRegistry")]
    partial class InitialRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ReviewAgent.Data.ReviewFindingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("ReviewAgent.Data.ReviewRunRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbortReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Complexity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("CriticalCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DegradationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiffLines")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionModel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FindingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraphQueries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GraphStatus")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuardrailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImpactChunks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelCalls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RouteJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "StartedAt");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("ReviewAgent.Data.WatchedRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GraphEdges")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GraphNodes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HookInstalled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HookInstalledAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastIndexError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastIndexedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ReviewAgent.Data.ReviewFindingRecord", b =>
                {
                    b.HasOne("ReviewAgent.Data.ReviewRunRecord", "Run")
                        .WithMany("Findings")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ReviewAgent.Data.ReviewRunRecord", b =>
                {
                    b.HasOne("ReviewAgent.Data.WatchedRepository", "Repository")
                        .WithMany("Runs")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("ReviewAgent.Data.ReviewRunRecord", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ReviewAgent.Data.WatchedRepository", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
